#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ ! -f .env ]; then
    cp .env.example .env
    php artisan key:generate
fi

npm install
npm run build
